export const images = [
  { src: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&q=80&w=400", color: "bg-white/50" },
  { src: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&q=80&w=400", color: "bg-white/50" },
  { src: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=400", color: "bg-white/50" },
  { src: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400", color: "bg-white/50" },
  { src: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400", color: "bg-white/50" },
  { src: "https://images.unsplash.com/photo-1554151228-14d9def656e4?auto=format&fit=crop&q=80&w=400", color: "bg-white/50" },
];
export const nameSuggestions = [
  "Nexus", "Cypher", "Pixel", "Vector", "Bit", "Logic", "Data", "Proxy", "Macro", "Syntax",
  "Zenith", "Aura", "Vortex", "Static", "Portal", "Matrix", "Bypass", "Buffer", "Cortex", "Binary",
  
  "Nebula", "Atlas", "Echo", "Nova", "Solar", "Lunar", "Orion", "Willow", "Terra", "Cosmos",
  "River", "Flint", "Ridge", "Summit", "Cedar", "Jasper", "Aster", "Solstice", "Zephyr", "Pinnacle",
  
  "Mochi", "Bento", "Koda", "Pippin", "Zippy", "Gidget", "Uno", "Tofu", "Milo", "Button"
];

export const dayNames = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
export const cooldown_time = 1000 * 60;
export const unprotected_routes = [
  "/",
  "/login",
  "/connect",
  "/help",
  "/pnp",
  "/tnc",
];
export const monthNames = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
export const nouns = [
  "agent",
  "arc",
  "asteroid",
  "beacon",
  "binary",
  "bit",
  "blade",
  "block",
  "bot",
  "bridge",
  "catalyst",
  "cell",
  "cipher",
  "clause",
  "code",
  "core",
  "cosmos",
  "crystal",
  "cue",
  "curve",
  "data",
  "delta",
  "drone",
  "echo",
  "edge",
  "element",
  "engine",
  "ether",
  "field",
  "file",
  "flare",
  "flow",
  "flux",
  "force",
  "frame",
  "gate",
  "grid",
  "halo",
  "horizon",
  "hub",
  "idea",
  "ink",
  "input",
  "insight",
  "key",
  "knot",
  "law",
  "leaf",
  "lens",
  "link",
  "loop",
  "map",
  "matrix",
  "mind",
  "mode",
  "molecule",
  "motion",
  "neuron",
  "node",
  "nova",
  "orbit",
  "origin",
  "output",
  "page",
  "path",
  "pattern",
  "peak",
  "phase",
  "pixel",
  "portal",
  "pulse",
  "quanta",
  "query",
  "qubit",
  "range",
  "ray",
  "realm",
  "record",
  "ring",
  "root",
  "scope",
  "script",
  "sensor",
  "shell",
  "signal",
  "spark",
  "stack",
  "stone",
  "stream",
  "string",
  "switch",
  "symbol",
  "sync",
  "system",
  "tag",
  "theorem",
  "thread",
  "token",
  "tool",
  "vault",
  "vector",
  "vertex",
  "vibe",
  "wave",
  "word",
  "zone",
];
export const adjectives = [
  "agile",
  "ancient",
  "artful",
  "atomic",
  "bold",
  "brave",
  "brilliant",
  "bubbly",
  "calm",
  "candid",
  "clever",
  "cloudy",
  "cosmic",
  "crafty",
  "crisp",
  "curious",
  "daring",
  "dazzling",
  "deep",
  "delightful",
  "dynamic",
  "eager",
  "elegant",
  "electric",
  "epic",
  "fancy",
  "fast",
  "fierce",
  "fluent",
  "flying",
  "focused",
  "fresh",
  "galactic",
  "gentle",
  "glorious",
  "glowing",
  "graceful",
  "grand",
  "gutsy",
  "happy",
  "hearty",
  "hidden",
  "honest",
  "icy",
  "ideal",
  "ingenious",
  "inspired",
  "intense",
  "jolly",
  "joyful",
  "keen",
  "kind",
  "lively",
  "logical",
  "loyal",
  "lucid",
  "lucky",
  "lunar",
  "mighty",
  "modern",
  "modest",
  "mystic",
  "nifty",
  "nimble",
  "noble",
  "novel",
  "open",
  "orbital",
  "patient",
  "peaceful",
  "pixelated",
  "polished",
  "precise",
  "proud",
  "quick",
  "quiet",
  "radiant",
  "rapid",
  "rare",
  "ready",
  "resilient",
  "robust",
  "sacred",
  "safe",
  "savvy",
  "sharp",
  "shiny",
  "silent",
  "slick",
  "smart",
  "solid",
  "stellar",
  "strong",
  "swift",
  "tidy",
  "timely",
  "tranquil",
  "trusty",
  "unified",
  "vivid",
  "warm",
  "wild",
  "wise",
  "witty",
  "zesty",
  "zippy",
];
export const DEFAULT_PAGE = 1
export const DEFAULT_PAGE_SIZE = 10
export const MIN_PAGE_SIZE = 1;
export const MAX_PAGE_SIZE = 100;